#!/usr/bin/env python3
import sys


with open(sys.argv[1], "r") as file:
     for num in file:
          num = int(num)
          for div in range(2, num//2):
               if num % div == 0:
                    print("{}={}*{}".format(num, num//div, div))
                    break
